server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # toutes les routes renvoient versindex.html(pour éviter le 404)
    location / {
        try_files $uri $uri/ /index.html;
    }

    #proxy vers le backend FastAPI
    location /api/ {
        # proxy_pass http://backend:8000/; essai fa lasa le backend no vakianle railway
        proxy_pass https://audit-backend-production-c815.up.railway.app/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}