name: CI/CD - Audit stock

# déclencheur à chaque push ou pull request sur la branche main
on:
  push:
    branches: [main, try]
  pull_request:
    branches: [main, try]
  
# définir les jobs à exécuter (les étapes du pipeline)
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # étape 1 : checkout du code
      - name: Checkout code
        uses: actions/checkout@v4 # presque comme git clone

      # étape 2 : builder l'image backend
      - name: Builder l'image backend
        run: docker build -t audit-backend ./backend

      # étape 3 : builder l'image frontend
      - name: Builder l'image frontend
        run: docker build -t audit-frontend ./frontend

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    services:
      # lancer un conteneur PostgreSQL pour les tests
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: auditDb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        # le syntaxe >- colle tous ces lignes en une seule ligne

    steps:
      # étape 1 : checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # étape 2 : installer Python et les dépendances
      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Installer les dépendances
        run: | # le | indique que les lignes suivantes font partie de la même commande
          cd backend
          pip install -r requirements.txt

      - name: Lancer le backend en arrière-plan
        env:
          DATABASE_URL: postgres://postgres:Aero2024@localhost:5432/auditDb
        run: |
          cd backend
          uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5  # attendre que le backend soit prêt
      
      - name: Tester que l'APIR répond
        run: |
          curl -fail http://localhost:8000/docs || exit 1
          echo "Backend est opérationnel"

      # étape 3 : installer Node.js et les dépendances frontend
      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Installer les dépendances frontend
        run: |   
          cd frontend
          npm install
      
      - name: Vérifier que le frontend build correctement
        run: |
          cd frontend
          npm run build || exit 1
          echo "Frontend compilé"

  push-images:
    name: Push Docker Hub
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/try' # ne push que sur la branche try pour l'instant mais d'habitude on push sur main

    steps:
      #checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      #se connecter à Docker Hub
      - name: Se connecter à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # $ {{..}} injection de varianble dans GitHub Actions
          password: ${{ secrets.DOCKER_PASSWORD }} # secrets. données chiffrées et stockées dans les paramètres du repo GitHub
      
      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Builder et pusher l'image backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend # le chemin du Dockerfile
          push: true # indiquer qu'on veut pousser l'image après le build
          tags: |
            anjara23/audit-backend:latest
            anjara23/audit-backend:${{ github.sha }}
      
      - name: Builder et pusher l'image frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend 
          push: true
          tags: |
            anjara23/audit-frontend:latest
            anjara23/audit-frontend:${{ github.sha }}
      
      - name: Résumé du déploiement
        run: |
          echo "   Images publiées sur Docker Hub"
          echo "   anjara23/audit-backend:latest"
          echo "   anjara23/audit-frontend:latest"
          echo "   Tag commit : ${{ github.sha }}"

        